# Generated by Django 6.0.7 on 2026-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='family',
            name='uniq_fam_xref_per_tree',
        ),
        migrations.RemoveConstraint(
            model_name='individual',
            name='uniq_indi_xref_per_tree',
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(condition=models.Q(('xref_id', ''), _negated=True), fields=('tree', 'xref_id'), name='uniq_fam_xref_per_tree'),
        ),
        migrations.AddConstraint(
            model_name='individual',
            constraint=models.UniqueConstraint(condition=models.Q(('xref_id', ''), _negated=True), fields=('tree', 'xref_id'), name='uniq_indi_xref_per_tree'),
        ),
    ]
