# Generated by Django 6.0.7 on 2026-07-14 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_family_uniq_fam_xref_per_tree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('VIEWER', 'Lecture'), ('EDITOR', 'Édition')], default='VIEWER', max_length=6)),
                ('invited_by', models.EmailField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.tree')),
            ],
            options={
                'db_table': 'tree_shares',
                'ordering': ['email'],
                'constraints': [models.UniqueConstraint(fields=('tree', 'email'), name='uniq_share_per_tree')],
            },
        ),
    ]
